### ISSUE TITLE
booktoki 사이트가 작동되지 않습니다.

### ISSUE THREAD

**Issue by Brian-Jurn** [STR-HK/hdl-stubs#4]
2024년 5월 경부터 booktoki 코드가 작동하지 않네요.. v1, v2, v3 전부 안됩니다.

다운로드 시도 시 오류 메시지는 아래와 같습니다(v2 기준)

Invalid: [booktoki] https://booktoki337.com/novel/14422189

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 5 / False / 15dc74796eef44dda0764195b542ded9
input: https://booktoki337.com/novel/14422189
type: booktoki
single: False
url: https://booktoki337.com/novel/14422189
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1715536703.0473318 (24-05-12 17:58:23 UTC) - 111s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_0", line 30, in read
 File "dynamic_module_0", line 131, in get_artist
 File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (3.5s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_1", line 30, in read
 File "dynamic_module_1", line 131, in get_artist
 File "dynamic_module_1", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (4.6s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_2", line 30, in read
 File "dynamic_module_2", line 102, in get_artist
 File "dynamic_module_2", line 88, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (3.5s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_0", line 30, in read
 File "dynamic_module_0", line 131, in get_artist
 File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (4.5s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_1", line 30, in read
 File "dynamic_module_1", line 131, in get_artist
 File "dynamic_module_1", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (8.8s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_0", line 30, in read
 File "dynamic_module_0", line 131, in get_artist
 File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (5.6s)

'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_0", line 30, in read
 File "dynamic_module_0", line 131, in get_artist
 File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki337.com/novel/14422189  (3.5s)

**Comment by STR-HK** [comment]
![image](https://github.com/STR-HK/hdl-stubs/assets/78652371/5785df6a-ba03-4fa9-85bb-18b034c62c4e)
재현할 수 없네요.

**Comment by Brian-Jurn** [comment]
해결했습니다. STR-HK께서 정상적으로 다운이 잘 되니 스크립트 문제가 아니라 네트워크 설정(쿠키, CAPTCHA 등) 문제임이 의심되어 그쪽을 파고들었더니 해결되었습니다. 사이트가 이전과 달리 cloudflare를 통해 사람인지 확인하는 CAPTCHA를 도입했는데, 제 네트워크 설정이나 ip 문제인지는 몰라도 그냥 다운로드 버튼을 누르니 CAPTCHA가 안풀리면서 다운이 안되는 것이었고, hitomi-downloader 내장 브라우저를 킨 상태에서 다운로드를 시도하니 자동으로 CAPTCHA가 풀리면서 다운이 정상적으로 잘 됩니다.
새벽에도 질문에 답변해 주셔서 감사합니다.
